{{- if .Values.deploymentSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cortex-xdr.deploymentSecretName" . }}
type: Opaque
stringData:
  distribution-id: {{ .Values.agent.distributionId | quote }}
{{- if .Values.agent.distributionServer }}
  distribution-server: {{ .Values.agent.distributionServer }}
{{- end }}
{{- end }}
